INSERT INTO books VALUES 

(5,9780312550981,'Beautiful: The Life of Hedy Lamarr','Stephen Michael Shearer, Robert Osborne','Non-Fiction','The Surprising Story of Hedy Lamarr, “The Most Beautiful Girl in the World”\n\nAs a teenage actress in 1920s Austria, performing on the stage and in film in light comedies and musicals, Hedy Kiesler, with her exotic beauty, was heralded across Europe by her mentor, Max Reinhardt. However, it was her nude scene, and surprising dramatic ability, in Ecstasy that made her a star. Ecstasy’s notoriety followed her for the rest of her life. She married one of Austria’s most successful and wealthy munitions barons, giving up her career for what seemed at first a fairy-tale existence. Instead, as war clouds loomed in the mid-1930s, Hedy discovered that she was trapped in a loveless marriage to a controlling, ruthless man who befriended Mussolini, sold armaments to Hitler, yet hid his own Jewish heritage to become an “honorary Aryan.”\n\nShe fled her husband and escaped to Hollywood, where M-G-M changed her name to Hedy Lamarr and she became one of film’s most glamorous stars. She worked with such renowned directors as King Vidor, Victor Fleming, and Cecil B. DeMille, and appeared opposite such respected actors as Clark Gable, Spencer Tracy, John Garfield, and James Stewart. But as her career waned, her personal problems and legal wranglings cast lingering shadows over her former image. It wasn’t until decades later that the world was stunned to learn of her unexpected role as the inventor of a technology that has become an essential part of everything from military weaponry to cell phones—proof that Hedy Lamarr was far more than merely Delilah to Victor Mature’s Samson. She demonstrated a creativity and an intelligence she had always possessed.\n\nStephen Michael Shearer’s in-depth and meticulously researched biography, written with the cooperation of Hedy’s children, intimate friends, and colleagues, separates the truths from the rumors, the facts from the fables, about Hedy Lamarr, to reveal the life and character of one of classic Hollywood’s most beautiful and remarkable women.','https://images-na.ssl-images-amazon.com/images/I/41FeLEsAq4L._SX328_BO1,204,203,200_.jpg'),

(4,9780321657299,'Rocket Surgery Made Easy: The Do-It-Yourself Guide to Finding and Fixing Usability Problems','Steve Krug','Non-Fiction','It has been known for years that usability testing can dramatically improve products. But with a typical price tag of $5,000 to $10,000 for a usability consultant to conduct each round of tests, it rarely happens. \n\nIn this how-to companion to Don\'t Make Me Think: A Common Sense Approach to Web Usability, Steve Krug spells out a streamlined approach to usability testing that anyone can easily apply to their own Web site, application, or other product. (As he said in Don\'t Make Me Think, \"It\'s not rocket surgery\".)\n\nUsing practical advice, plenty of illustrations, and his trademark humor, Steve explains how to: \nTest any design, from a sketch on a napkin to a fully-functioning Web site or application\nKeep your focus on finding the most important problems (because no one has the time or resources to fix them all)\nFix the problems that you find, using his \"The least you can do\" approach\nBy paring the process of testing and fixing products down to its essentials (\"A morning a month, that\'s all we ask\"), Rocket Surgery makes it realistic for teams to test early and often, catching problems while it\'s still easy to fix them. Rocket Surgery Made Easy adds demonstration videos to the proven mix of clear writing, before-and-after examples, witty illustrations, and practical advice that made Don\'t Make Me Think so popular.','https://images-na.ssl-images-amazon.com/images/I/51uKs9Nat8L._SX388_BO1,204,203,200_.jpg'),

(1,9780596527679,'The Art of Agile Development: Pragmatic Guide to Agile Software Development','James Shore, Shane Warden','Non-fiction','The Art of Agile Development contains practical guidance for anyone considering or applying agile development for building valuable software. Plenty of books describe what agile development is or why it helps software projects succeed, but very few combi...','https://images-na.ssl-images-amazon.com/images/I/41aJ%2B153qhL._SX379_BO1,204,203,200_.jpg'),

(3,9781681883816,'The Sawbones Book: The Hilarious, Horrifying Road to Modern Medicine','Justin McElroy (Author), Dr. Sydnee McElroy (Author), Teylor Smirl (Illustrator)','Humor','Wondering whether eating powdered mummies might be just the thing to cure your ills? Tempted by those vintage ads suggesting you wear radioactive underpants for virility? Ever considered drilling a hole in your head to deal with those pesky headaches? Probably not. But for thousands of years, people have done things like this—and things that make radioactive underpants seem downright sensible! In their hit podcast, Sawbones, Sydnee and Justin McElroy breakdown the weird and wonderful way we got to modern healthcare. And some of the terrifying detours along the way.','https://images-na.ssl-images-amazon.com/images/I/61MiU0wLihL._SX397_BO1,204,203,200_.jpg'),

(2,9781786824813,'Emilia','Morgan Lloyd Malcolm','Play','The little we know of Emilia Bassano is restricted to the possibility that she may have been the ‘Dark Lady’ of Shakespeare’s Sonnets – and the rest of Her Story has been erased by History. Commissioned specifically for Shakespeare’s Globe, and with an all-female cast, this world premiere will reveal the life of Emilia: poet, mother and feminist. This time, the focus will be on this exceptional woman who managed to outlive all the men the history books tethered her to.','https://images-na.ssl-images-amazon.com/images/I/41xLQ%2BDXvbL._SX305_BO1,204,203,200_.jpg');

INSERT INTO collections VALUES (1,1,9780312550981,0,1,'New'),(2,1,9780321657299,0,1,'New'),(3,1,9780596527679,0,1,'New'),(4,1,9781681883816,0,1,'New'),(5,1,9781786824813,0,1,'New');

INSERT INTO raiders VALUES (1,'carolyn','carolynwk@gmail.com', 'xyz');